language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.0
  - 7.1
  - nightly
  
services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci;'
  
matrix:
  allow_failures:
    - php: nightly

sudo: false

install:
  - if [[ "$BUILD" != true ]]; then
      composer require satooshi/php-coveralls:~0.6@stable;
    fi

before_script:
  - if [[ "$BUILD" != true ]]; then
      mkdir -p build/logs;
      composer create-project october/october october;
      sed -i "s/'database'  => 'database',/'database'  => 'test',/" october/config/database.php;
      php october/artisan october:up;
      php october/artisan plugin:install Lovata.Toolbox;
      mkdir -p ./october/plugins/lovata/shopaholic;
      mv !(october) october/plugins/lovata/shopaholic;
      cd october/plugins/lovata/shopaholic;
    fi

script:
  - ../../../vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - if [[ "$BUILD" != true ]]; then
      sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
    fi

jobs:
  include:
    - stage: Release
      env:
        - BUILD=true
      script:
        - NAME="shopaholic"
        - zip -r $NAME ./ -x .git/\* -x .gitignore -x .travis.yml -x crowdin.yml -x .editorconfig
        - TAG=$(git describe --tags)
        - FILE="./$NAME.zip"
        - if [[ -e $FILE ]]; then
            NEW_NAME="$NAME-$TAG.$TRAVIS_JOB_ID";
            mv $NAME.zip $NEW_NAME.zip;
          fi
      deploy:
        provider: releases
        api_key: c73a4d454db31a4e70c2281d72e67b5b943e287e
        file: "$NEW_NAME.zip"
        skip_cleanup: true
        on:
          tags: true
          repo: kharanenka/oc-shopaholic-plugin
